### ISSUE TITLE
Solteris - Auto Dispell specific buffs on NPC during Combat

### ISSUE THREAD

**Issue by Roxenrox** [morgs71/RoF2-E3-THF#11]
Any form of Dispell  Spell/Clicky seems to work 
But listening here the ones directly from Solteris i found so far since didn't see the need to Dispell anything before that point of progression.
Christine's Engagement Ring (Tier 9) - item
Flames of Annulment - spell

**Buffs that need the Dispelling** might add more 
Woven Fire - ${Target.Buff[Woven Fire].ID}
Infusion of the Inferno - ${Target.Buff[Infusion of the Inferno].ID}
Fiery Potential - ${Target.Buff[Fiery Potential].ID}

Maybe needed at some point in other Zones again.

**Comment by morgs71** [comment]
New Code added for this feature
