### ISSUE TITLE
Solteris - Automatically stop Melee from attacking if mob has DS

### ISSUE THREAD

**Issue by Roxenrox** [morgs71/RoF2-E3-THF#12]
Kinda related to #11 

if **${Target.Buff[Woven Fire].ID}** Melee DPS needs to stop attack 
after that 
if **!${Target.Buff[Woven Fire].ID}** needs to start attack,

**Comment by Roxenrox** [comment]
So far what i have 
/declare DSChecker int outer 0

Sub DS_Check
    /varset DSChecker 0
    /call IsTank
    
    /if (!${IsTank} && ${Select[${Me.Class.ShortName},MNK,BER,ROG,RNG,BST,BRD,WAR,PAL,SK]} && ${Target.Buff[Woven Fire].ID} && ${DSChecker}==0 ) {
        /delay 5
        /call AssistOff    
        /varset DSChecker 1
    } else /if (${DSChecker}==1 && !${Target.Buff[Woven Fire].ID}) {
        /varset DSChecker 0
    } else /if ($(IsTank) && !${Target.Buff[Woven Fire].ID}) {
        /bc Assist ${TankName} on ${Target.ID}    
    }
    /return

**Comment by Roxenrox** [comment]
Still working on it at the moment it works as far as Melee stop attacking on initial DS pull.
However some pets still die and need to ensure after, that it also works with reapplied DS buff.

**Comment by morgs71** [comment]
New Code Added for this feature
