### ISSUE TITLE
Update Cleric AE-Rez command to first ask for consent, similar to the /gathercorpses command

### ISSUE THREAD

**Issue by conorhodder** [morgs71/RoF2-E3-THF#15]
Add new line 118-119

  /consentme

**Comment by Roxenrox** [comment]
Well yes AE-Rez command spits usually error out but it still  works if fine if you have the consent setup under options in the client.
Only issue might be if you use it on someone who doesn't have there consent set.

**Comment by morgs71** [comment]
Code Accepted & Added...Thank you!
